# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 364fdf16f89a84bb4783442db71001405b2473778ab705fa58bd8eb9678ae1e13fa48410a23c94c97a82d0302a76fce5dff7f54e3159051dd1ac57dc205c080e

test:
  secret_key_base: e001da8e287953b9ee8303a177e24f992ea1504941796735070262e522f51112d46b4fd694df9ee8aa3bedfda61f363dbd7780ae42376f1522b8858989f83a1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
